### ISSUE TITLE
Bot crashes after last commit

### ISSUE THREAD

**Issue by sawankumar** [Loli-Killer/TgFolderClone#2]
Bot is crashing after last commit [#fefae9c](https://github.com/Loli-Killer/TgFolderClone/commit/fefae9c02b627ae600c10e2e6eca6aaa9be0a224)

2020-07-27T10:28:15.398064+00:00 app[worker.1]: Traceback (most recent call last):
2020-07-27T10:28:15.398120+00:00 app[worker.1]:   File "folderclone.py", line 430, in <module>
2020-07-27T10:28:15.402500+00:00 app[worker.1]:     main()
2020-07-27T10:28:15.402534+00:00 app[worker.1]:   File "folderclone.py", line 420, in main
2020-07-27T10:28:15.402977+00:00 app[worker.1]:     mfc.clone()
2020-07-27T10:28:15.403005+00:00 app[worker.1]:   File "folderclone.py", line 389, in clone
2020-07-27T10:28:15.403380+00:00 app[worker.1]:     self._rcopy(self.source, i, root_dir, '', self.width)
2020-07-27T10:28:15.403409+00:00 app[worker.1]:   File "folderclone.py", line 272, in _rcopy
2020-07-27T10:28:15.403728+00:00 app[worker.1]:     fullname = fullname.encode(self.encoding, errors='replace').decode(self.encoding)
2020-07-27T10:28:15.403826+00:00 app[worker.1]: TypeError: encode() argument 1 must be str, not None
2020-07-27T10:32:11.826783+00:00 app[worker.1]: An uncaught error was raised while running the promise
2020-07-27T10:32:11.826834+00:00 app[worker.1]: Traceback (most recent call last):
2020-07-27T10:32:11.826835+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/telegram/utils/promise.py", line 56, in run
2020-07-27T10:32:11.826836+00:00 app[worker.1]:     self._result = self.pooled_function(*self.args, **self.kwargs)
2020-07-27T10:32:11.826836+00:00 app[worker.1]:   File "clonerbot.py", line 179, in stop
2020-07-27T10:32:11.826836+00:00 app[worker.1]:     subprocess.call(['taskkill', '/F', '/T', '/PID',  str(proc.pid)])
2020-07-27T10:32:11.826837+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute ['pid'[](url)](url)

**Comment by Neppu-Nep** [comment]
Fixed in the latest commit : c01ea077460e1f40c70ffe35718226d6c8b1c42a
