### ISSUE TITLE
Again Timeout Error :(

### ISSUE THREAD

**Issue by sawankumar** [Loli-Killer/TgFolderClone#3]
_Tried Coping 8TB and it throws Timeout Error._

**Logs :-**

2020-07-29T12:39:14.692732+00:00 app[worker.1]: An uncaught error was raised while running the promise
2020-07-29T12:39:14.692742+00:00 app[worker.1]: Traceback (most recent call last):
2020-07-29T12:39:14.692742+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/telegram/utils/promise.py", line 56, in run
2020-07-29T12:39:14.692743+00:00 app[worker.1]:     self._result = self.pooled_function(*self.args, **self.kwargs)
2020-07-29T12:39:14.692743+00:00 app[worker.1]:   File "clonerbot.py", line 158, in clone
2020-07-29T12:39:14.692744+00:00 app[worker.1]:     message.edit_text(to_send)
2020-07-29T12:39:14.692744+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/telegram/message.py", line 876, in edit_text
2020-07-29T12:39:14.692745+00:00 app[worker.1]:     chat_id=self.chat_id, message_id=self.message_id, *args, **kwargs)
2020-07-29T12:39:14.692745+00:00 app[worker.1]:   File "<decorator-gen-27>", line 2, in edit_message_text
2020-07-29T12:39:14.692745+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/telegram/bot.py", line 67, in decorator
2020-07-29T12:39:14.692746+00:00 app[worker.1]:     result = func(*args, **kwargs)
2020-07-29T12:39:14.692746+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/telegram/bot.py", line 1898, in edit_message_text
2020-07-29T12:39:14.692746+00:00 app[worker.1]:     return self._message(url, data, timeout=timeout, reply_markup=reply_markup, **kwargs)
2020-07-29T12:39:14.692747+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/telegram/bot.py", line 175, in _message
2020-07-29T12:39:14.692747+00:00 app[worker.1]:     result = self._request.post(url, data, timeout=timeout)
2020-07-29T12:39:14.692747+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/telegram/utils/request.py", line 333, in post
2020-07-29T12:39:14.692747+00:00 app[worker.1]:     **urlopen_kwargs)
2020-07-29T12:39:14.692748+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/telegram/utils/request.py", line 237, in _request_wrapper
2020-07-29T12:39:14.692748+00:00 app[worker.1]:     message = self._parse(resp.data)
2020-07-29T12:39:14.692748+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/telegram/utils/request.py", line 195, in _parse
2020-07-29T12:39:14.692756+00:00 app[worker.1]:     raise RetryAfter(retry_after)
2020-07-29T12:39:14.692756+00:00 app[worker.1]: telegram.error.RetryAfter: Flood control exceeded. Retry in 9 seconds

**Comment by Neppu-Nep** [comment]
Should be fixed in 450eae3e58dddc08fa980c037703742ced64d8ae

**Comment by sawankumar** [comment]
@Loli-Killer Not Fixed. Same issue.

**Comment by sawankumar** [comment]
@Loli-Killer Using docker might fix this time out error. 

Checkout this : https://github.com/smartass08/telegram_gcloner/commit/07fdaf43bfce21b361b77ca12b6b9e13442627fb
